# Generated by Django 2.1 on 2018-08-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180825_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('dhcp_status', models.BooleanField(default=False)),
                ('nightbus_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='KakaoDHCPService',
        ),
    ]
