# Generated by Django 2.1.1 on 2018-09-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180829_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakaoservice',
            name='id',
        ),
        migrations.AddField(
            model_name='kakaoservice',
            name='paidtoilet_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kakaoservice',
            name='user',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
