# Generated by Django 2.1.1 on 2018-10-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_webguiderequests_request_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webguiderequests',
            name='request_content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
