# Generated by Django 2.1.1 on 2018-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181010_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webguiderequests',
            name='request_content',
            field=models.TextField(blank=True),
        ),
    ]
