# Generated by Django 2.1.1 on 2018-10-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181010_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webguiderequests',
            name='request_content',
        ),
    ]
