# Generated by Django 2.1 on 2018-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_webguiderequests_request_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGuideReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_time', models.DateTimeField(auto_now=True)),
                ('request_id', models.IntegerField()),
                ('reply_content', models.TextField(blank=True)),
            ],
        ),
    ]
