# Generated by Django 2.1.1 on 2018-11-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_webguidereplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webguidereplies',
            name='reply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webguiderequests',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
