# Generated by Django 3.0.3 on 2020-09-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181121_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KakaoService',
        ),
    ]
