# Generated by Django 3.1.5 on 2021-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_kakaoservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPubTransRoutesComparisons',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
