# Generated by Django 3.2.2 on 2021-05-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_webbustimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbustimetable',
            name='update_date',
            field=models.DateField(),
        ),
    ]
